#CPU = msp430fxyz
#CPU_MODEL = msp430f1612

CPU = msp430-sancus
#CPU_MODEL = msp430f5438
CPU_MODEL = msp430f149


# Put defined MCU peripherals here (in alphabetical order)
#FEATURES_PROVIDED += periph_gpio periph_gpio_irq
#FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart

